import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import proPic from "../../public/images/profile/proPic1.png"
import AnimatedText from '@/components/AnimatedText'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0 '>
          <div className='flex items-center justify-between w-full'>
              <div className='w-1/2'>
                <Image src={proPic} alt="shamly" className='w-full h-auto '/>
              </div>
              <div className='w-1/2 flex flex-col items-center self-center'>
                <p>hey there,I&apos;m</p>
                <AnimatedText text="Shamly Shanawaz" className='!text-6xl !text-left'/>
                <p>A technically competent and self-motivated undergraduate with qualitative academic college experience in the field of ICT. An effective team player who leverages technical, leadership and communication skills to achieve goals and one who continuously seeks opportunities to master new technologies.</p>
              </div>
          </div>
        </Layout>
      </main>      
    </>
  )
}
